
WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).


WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).


WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).

2023-06-02 00:12:11,359:INFO:mapsims:Parsing configuration from common.toml, tsz_tsz1.toml
2023-06-02 00:12:11,370:INFO:mapsims:Nside: 4096, Modeling Nside: 8192, Ellmax: 10240
Traceback (most recent call last):
  File "/mnt/home/azonca/mambaforge-pypy3/envs/so/bin/mapsims_run", line 8, in <module>
    sys.exit(command_line_script())
  File "/mnt/home/azonca/mambaforge-pypy3/envs/so/lib/python3.10/site-packages/mapsims/runner.py", line 176, in command_line_script
    simulator = from_config(res.config, override=override)
  File "/mnt/home/azonca/mambaforge-pypy3/envs/so/lib/python3.10/site-packages/mapsims/runner.py", line 259, in from_config
    map_sim = MapSim(
  File "/mnt/home/azonca/mambaforge-pypy3/envs/so/lib/python3.10/site-packages/mapsims/runner.py", line 437, in __init__
    os.makedirs(self.output_folder)
  File "/mnt/home/azonca/mambaforge-pypy3/envs/so/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'output/tsz_tsz1'

real	0m1.746s
user	0m2.350s
sys	0m3.617s
