
WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).


WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).


WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).

2023-06-02 00:37:22,579:INFO:mapsims:Parsing configuration from common.toml, co_co3.toml
2023-06-02 00:37:22,607:INFO:mapsims:Nside: 4096, Modeling Nside: 2048, Ellmax: 5120
2023-06-02 00:37:22,608:INFO:mapsims:Initializing the PySM Sky object
2023-06-02 00:37:22,609:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/HFI_CompMap_CO-Type1_2048_R2.00_ring.fits
2023-06-02 00:37:22,610:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/HFI_CompMap_CO-Type1_2048_R2.00_ring.fits
2023-06-02 00:37:41,117:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/psimap_dust90_2048.fits
2023-06-02 00:37:41,118:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/psimap_dust90_2048.fits
2023-06-02 00:37:42,722:WARNING:pysm3:No physical unit associated with file /mnt/sdceph/users/azonca/pysm-data/co/psimap_dust90_2048.fits
2023-06-02 00:37:42,723:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/gmap_dust90_2048.fits
2023-06-02 00:37:42,724:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/gmap_dust90_2048.fits
2023-06-02 00:37:55,525:WARNING:pysm3:No physical unit associated with file /mnt/sdceph/users/azonca/pysm-data/co/gmap_dust90_2048.fits
2023-06-02 00:37:55,526:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/mcmoleCO_HGL_2048.fits
2023-06-02 00:37:55,527:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/mcmoleCO_HGL_2048.fits
2023-06-02 00:38:00,074:INFO:mapsims:Processing channel Channel SPLAT_f280
2023-06-02 00:38:00,074:INFO:mapsims:Bandpass integration for Channel SPLAT_f280
2023-06-02 00:38:01,233:INFO:mapsims:Smoothing and coord-transform for Channel SPLAT_f280
/mnt/home/azonca/mambaforge-pypy3/envs/so/lib/python3.10/site-packages/healpy/sphtfunc.py:414: RuntimeWarning: invalid value encountered in double_scalars
  return realalm2alm(res[0]), res[3] / norm(maps.reshape((-1,))), res[2]
2023-06-02 00:38:11,148:INFO:pysm3:Used map2alm_lsq, converged in 0 iterations,residual relative error nan
2023-06-02 00:38:11,148:INFO:pysm3:Smoothing with fwhm of 1.0 arcmin
2023-06-02 00:38:12,083:INFO:pysm3:Rotate Alm
2023-06-02 00:39:28,998:INFO:pysm3:Alm to map HEALPix
2023-06-02 00:39:40,082:INFO:mapsims:Writing output map cmbs4_co_co3_uKCMB_LAT-SPLAT_f280_nside4096.fits
2023-06-02 00:39:40,082:INFO:mapsims:Replace NaN with UNSEEN
2023-06-02 00:39:40,818:INFO:mapsims:Reorder ring to nest
2023-06-02 00:39:57,030:INFO:mapsims:Writing output map

real	3m9.547s
user	64m24.108s
sys	0m46.528s
